# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RPCserver.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RPCserver.proto',
  package='RPCserver',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fRPCserver.proto\x12\tRPCserver\"\r\n\x0bPingRequest\"\x19\n\tPongReply\x12\x0c\n\x04pong\x18\x01 \x01(\t\"@\n\rUploadRequest\x12\x0e\n\x06\x62inary\x18\x01 \x01(\x0c\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"\x1e\n\x0bResultReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\x91\x01\n\x0fServerInterface\x12<\n\nTestStatus\x12\x16.RPCserver.PingRequest\x1a\x14.RPCserver.PongReply\"\x00\x12@\n\nImageStore\x12\x18.RPCserver.UploadRequest\x1a\x16.RPCserver.ResultReply\"\x00\x62\x06proto3')
)




_PINGREQUEST = _descriptor.Descriptor(
  name='PingRequest',
  full_name='RPCserver.PingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=43,
)


_PONGREPLY = _descriptor.Descriptor(
  name='PongReply',
  full_name='RPCserver.PongReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pong', full_name='RPCserver.PongReply.pong', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=70,
)


_UPLOADREQUEST = _descriptor.Descriptor(
  name='UploadRequest',
  full_name='RPCserver.UploadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='binary', full_name='RPCserver.UploadRequest.binary', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='RPCserver.UploadRequest.uuid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='RPCserver.UploadRequest.timestamp', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=136,
)


_RESULTREPLY = _descriptor.Descriptor(
  name='ResultReply',
  full_name='RPCserver.ResultReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='RPCserver.ResultReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=168,
)

DESCRIPTOR.message_types_by_name['PingRequest'] = _PINGREQUEST
DESCRIPTOR.message_types_by_name['PongReply'] = _PONGREPLY
DESCRIPTOR.message_types_by_name['UploadRequest'] = _UPLOADREQUEST
DESCRIPTOR.message_types_by_name['ResultReply'] = _RESULTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PingRequest = _reflection.GeneratedProtocolMessageType('PingRequest', (_message.Message,), dict(
  DESCRIPTOR = _PINGREQUEST,
  __module__ = 'RPCserver_pb2'
  # @@protoc_insertion_point(class_scope:RPCserver.PingRequest)
  ))
_sym_db.RegisterMessage(PingRequest)

PongReply = _reflection.GeneratedProtocolMessageType('PongReply', (_message.Message,), dict(
  DESCRIPTOR = _PONGREPLY,
  __module__ = 'RPCserver_pb2'
  # @@protoc_insertion_point(class_scope:RPCserver.PongReply)
  ))
_sym_db.RegisterMessage(PongReply)

UploadRequest = _reflection.GeneratedProtocolMessageType('UploadRequest', (_message.Message,), dict(
  DESCRIPTOR = _UPLOADREQUEST,
  __module__ = 'RPCserver_pb2'
  # @@protoc_insertion_point(class_scope:RPCserver.UploadRequest)
  ))
_sym_db.RegisterMessage(UploadRequest)

ResultReply = _reflection.GeneratedProtocolMessageType('ResultReply', (_message.Message,), dict(
  DESCRIPTOR = _RESULTREPLY,
  __module__ = 'RPCserver_pb2'
  # @@protoc_insertion_point(class_scope:RPCserver.ResultReply)
  ))
_sym_db.RegisterMessage(ResultReply)



_SERVERINTERFACE = _descriptor.ServiceDescriptor(
  name='ServerInterface',
  full_name='RPCserver.ServerInterface',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=171,
  serialized_end=316,
  methods=[
  _descriptor.MethodDescriptor(
    name='TestStatus',
    full_name='RPCserver.ServerInterface.TestStatus',
    index=0,
    containing_service=None,
    input_type=_PINGREQUEST,
    output_type=_PONGREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ImageStore',
    full_name='RPCserver.ServerInterface.ImageStore',
    index=1,
    containing_service=None,
    input_type=_UPLOADREQUEST,
    output_type=_RESULTREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVERINTERFACE)

DESCRIPTOR.services_by_name['ServerInterface'] = _SERVERINTERFACE

# @@protoc_insertion_point(module_scope)
